"use client";

import { useMemo } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Loader2, BookOpen, RefreshCcw, Sparkles, FileText } from "lucide-react";

interface ResearchTabProps {
  caseId: string;
}

const RESEARCH_HEADINGS = [
  "RELEVANT PRECEDENTS",
  "COUNTER-ARGUMENTS TO ANTICIPATE",
  "CROSS-EXAMINATION QUESTIONS",
];

function splitSections(content: string): Array<{ heading: string; body: string }> {
  const normalized = content || "";
  const sections: Array<{ heading: string; body: string }> = [];

  for (let i = 0; i < RESEARCH_HEADINGS.length; i += 1) {
    const heading = RESEARCH_HEADINGS[i];
    const nextHeading = RESEARCH_HEADINGS[i + 1];
    const start = normalized.indexOf(heading);
    if (start < 0) continue;

    const bodyStart = start + heading.length;
    const end = nextHeading ? normalized.indexOf(nextHeading, bodyStart) : normalized.length;
    const body = normalized.slice(bodyStart, end < 0 ? normalized.length : end).trim();
    sections.push({ heading, body });
  }

  if (sections.length === 0 && normalized.trim()) {
    sections.push({ heading: "Research Brief", body: normalized.trim() });
  }

  return sections;
}

export function ResearchTab({ caseId }: ResearchTabProps) {
  const queryClient = useQueryClient();

  const { data: notes = [], isLoading: notesLoading } = useQuery({
    queryKey: ["notes", caseId],
    queryFn: () => api.notes.getByCase(caseId),
  });

  const { data: analysis = [], isLoading: analysisLoading } = useQuery({
    queryKey: ["analysis", caseId],
    queryFn: () => api.analysis.getByCaseId(caseId),
  });

  const runAnalysisMutation = useMutation({
    mutationFn: () => api.analysis.runAnalysis(caseId),
    onSuccess: async () => {
      await Promise.all([
        queryClient.invalidateQueries({ queryKey: ["analysis", caseId] }),
        queryClient.invalidateQueries({ queryKey: ["notes", caseId] }),
      ]);
    },
  });

  const researchNotes = useMemo(() => {
    return notes.filter((n) => n.noteType === "research");
  }, [notes]);

  const autoBrief = useMemo(() => {
    return researchNotes.find((n) => n.autoGenerated || n.title === "Auto Research Brief");
  }, [researchNotes]);

  const manualNotes = useMemo(() => {
    return researchNotes.filter((n) => n.id !== autoBrief?.id);
  }, [researchNotes, autoBrief]);

  const parsedSections = useMemo(() => splitSections(autoBrief?.content || ""), [autoBrief]);

  const hasAnalysis = analysis.length > 0;
  const loading = notesLoading || analysisLoading;

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="flex items-center gap-2 text-lg font-semibold">
          <BookOpen className="h-5 w-5" />
          Research Brief
        </h3>
        <Button
          size="sm"
          onClick={() => runAnalysisMutation.mutate()}
          disabled={runAnalysisMutation.isPending || !hasAnalysis}
        >
          {runAnalysisMutation.isPending ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Generating
            </>
          ) : (
            <>
              <RefreshCcw className="mr-2 h-4 w-4" />
              {autoBrief ? "Regenerate Brief" : "Generate Brief"}
            </>
          )}
        </Button>
      </div>

      {!hasAnalysis ? (
        <Card>
          <CardContent className="py-8 text-center text-muted-foreground">
            <BookOpen className="mx-auto mb-3 h-10 w-10 opacity-30" />
            <p className="mb-3">Run analysis first to generate an auto research brief.</p>
            <Button size="sm" onClick={() => runAnalysisMutation.mutate()} disabled={runAnalysisMutation.isPending}>
              {runAnalysisMutation.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
              Run Analysis
            </Button>
          </CardContent>
        </Card>
      ) : null}

      {hasAnalysis && !autoBrief ? (
        <Card>
          <CardContent className="py-8 text-center text-muted-foreground">
            <Sparkles className="mx-auto mb-3 h-10 w-10 opacity-30" />
            <p className="mb-3">No auto-generated brief yet. Generate one from the latest analysis findings.</p>
            <Button size="sm" onClick={() => runAnalysisMutation.mutate()} disabled={runAnalysisMutation.isPending}>
              {runAnalysisMutation.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
              Generate Brief
            </Button>
          </CardContent>
        </Card>
      ) : null}

      {autoBrief ? (
        <Card className="border-blue-200 bg-blue-50/40">
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-base">
              <Sparkles className="h-4 w-4 text-blue-600" />
              Auto Research Brief
              <Badge variant="outline" className="border-blue-300 text-blue-700">Auto</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {parsedSections.map((section) => (
              <div key={section.heading} className="space-y-1">
                <h4 className="text-sm font-semibold tracking-wide text-blue-900">{section.heading}</h4>
                <p className="whitespace-pre-wrap text-sm text-slate-700">{section.body || "Further research needed"}</p>
              </div>
            ))}
            <p className="text-xs text-muted-foreground">Updated: {autoBrief.updatedAt}</p>
          </CardContent>
        </Card>
      ) : null}

      {manualNotes.length > 0 ? (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-base">
              <FileText className="h-4 w-4" />
              Additional Research Notes ({manualNotes.length})
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            {manualNotes.map((note) => (
              <div key={note.id} className="rounded-md border bg-background p-3">
                <p className="text-sm font-medium">{note.title || "Research Note"}</p>
                <p className="mt-1 whitespace-pre-wrap text-sm text-muted-foreground">{note.content}</p>
              </div>
            ))}
          </CardContent>
        </Card>
      ) : null}
    </div>
  );
}
