// ─── Case Room ───────────────────────────────────────────────

export type CaseType = "Criminal" | "Civil" | "Civil - Tax" | "Civil - Property" | "Corporate" | "Family" | "Property" | "Other";
export type CaseStage = "Investigation" | "Bail Stage" | "Evidence" | "Arguments" | "Trial" | "Mediation" | "Discovery" | "Appeal" | "Judgment Pending";
export type PartyRole = "Accused" | "Petitioner" | "Respondent" | "Complainant" | "Witness" | "Lawyer";

export interface Party {
  id: string;
  name: string;
  role: PartyRole;
  notes?: string;
  partyType?: string;
  advocateName?: string;
  barCouncilNumber?: string;
  contactPhone?: string;
  contactEmail?: string;
  address?: string;
}

export interface CaseRoom {
  id: string;
  title: string;
  caseNumber: string;
  court: string;
  caseType: CaseType;
  stage: CaseStage;
  documentCount: number;
  loopholesDetected: number;
  nextHearing: string;
  strength: number;
  status: "active" | "archived" | "pending";
  createdAt: string;
  parties: Party[];
  venue: string;
  // New fields
  filingDate?: string;
  filingNumber?: string;
  firNumber?: string;
  policeStation?: string;
  judgeName?: string;
  courtNumber?: string;
  applicableSections?: string[];
  caseDescription?: string;
  priority?: string;
  clientName?: string;
  clientPhone?: string;
  clientEmail?: string;
  opposingCounsel?: string;
  hearingCount?: number;
  taskCount?: number;
  noteCount?: number;
}

// ─── Wizard ──────────────────────────────────────────────────

export interface CaseWizardData {
  caseInfo: {
    title: string;
    caseNumber: string;
    court: string;
    caseType: CaseType;
    stage: CaseStage;
    nextHearing: string;
    filingDate?: string;
    filingNumber?: string;
    firNumber?: string;
    policeStation?: string;
    judgeName?: string;
    courtNumber?: string;
    applicableSections?: string[];
    caseDescription?: string;
    priority?: string;
    clientName?: string;
    clientPhone?: string;
    clientEmail?: string;
    opposingCounsel?: string;
  };
  parties: Party[];
  documents: File[];
}

// ─── Documents ───────────────────────────────────────────────

export interface Document {
  id: string;
  name: string;
  type: string;
  size: string;
  uploadDate: string;
  status: "uploaded" | "processing" | "analyzed" | "error";
  pages: number;
  hasText?: boolean;
  chunkCount?: number;
}

// ─── Analysis ────────────────────────────────────────────────

export interface AnalysisResult {
  id: string;
  type: "loophole" | "contradiction" | "argument" | "gap";
  severity: "high" | "medium" | "low";
  title: string;
  description: string;
  legalBasis: string;
  guidance: string;
  documentRef: string;
  page: number;
}

export type AnalysisStage =
  | "reading"
  | "extracting"
  | "compliance"
  | "contradictions"
  | "precedents"
  | "timeline";

export interface AnalysisProgress {
  stage: AnalysisStage;
  label: string;
  complete: boolean;
}

// ─── Chat ────────────────────────────────────────────────────

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: string;
  citations?: Citation[];
}

export interface Citation {
  document: string;
  page: number;
  text: string;
}

// ─── Drafts ──────────────────────────────────────────────────

export interface DraftTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
}

// ─── Timeline ────────────────────────────────────────────────

export interface TimelineEvent {
  id: string;
  eventType: string;
  title: string;
  description: string;
  eventDate: string;
  status: "completed" | "current" | "upcoming";
  autoGenerated: boolean;
  linkedDocumentId?: string;
  linkedHearingId?: string;
  createdAt: string;
}

// ─── Hearings ────────────────────────────────────────────────

export interface Hearing {
  id: string;
  caseId: string;
  hearingDate: string;
  hearingType: string;
  judgeName: string;
  courtNumber: string;
  outcome: string;
  nextDate?: string;
  notes: string;
  adjourned: boolean;
  adjournmentReason: string;
  orderText: string;
  orderDocumentId?: string;
  createdAt: string;
}

// ─── Tasks ───────────────────────────────────────────────────

export interface Task {
  id: string;
  caseId: string;
  title: string;
  description: string;
  dueDate?: string;
  priority: "low" | "medium" | "high" | "urgent";
  status: "todo" | "in_progress" | "done" | "blocked";
  assignee: string;
  taskType: string;
  completedAt?: string;
  createdAt: string;
}

// ─── Notes ───────────────────────────────────────────────────

export interface CaseNote {
  id: string;
  caseId: string;
  title: string;
  content: string;
  noteType: string;
  isPrivate: boolean;
  createdAt: string;
  updatedAt: string;
}

// ─── Notifications ───────────────────────────────────────────

export interface Notification {
  id: string;
  caseId?: string;
  title: string;
  message: string;
  notificationType: string;
  isRead: boolean;
  createdAt: string;
}

// ─── Dashboard ───────────────────────────────────────────────

export interface DashboardStats {
  caseRooms: number;
  hearingsToday: number;
  aiAnalyses: number;
  draftsGenerated: number;
}

// ─── User ────────────────────────────────────────────────────

export interface User {
  id: string;
  name: string;
  email: string;
  plan: "free" | "pro" | "enterprise";
  avatar?: string;
}
