from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List

from app.database import get_db
from app.models import User, Case, Draft
from app.schemas.draft import DraftRequest, DraftResponse, DraftTemplateResponse
from app.utils.auth import get_current_user

router = APIRouter()

TEMPLATES = [
    DraftTemplateResponse(id="bail-application", name="Bail Application", description="Regular bail application under Section 439 CrPC", category="Criminal", icon="FileText"),
    DraftTemplateResponse(id="anticipatory-bail", name="Anticipatory Bail", description="Application for anticipatory bail under Section 438 CrPC", category="Criminal", icon="FileEdit"),
    DraftTemplateResponse(id="written-arguments", name="Written Arguments", description="Written arguments for submission during trial", category="Litigation", icon="Scale"),
    DraftTemplateResponse(id="legal-notice", name="Legal Notice", description="Formal legal notice under Section 80 CPC", category="Civil", icon="Mail"),
    DraftTemplateResponse(id="affidavit", name="Affidavit", description="Sworn affidavit for court submission", category="General", icon="UserCheck"),
    DraftTemplateResponse(id="petition", name="Writ Petition", description="Petition under Article 226/227 of the Constitution", category="Constitutional", icon="Scale"),
]


def _generate_draft_content(template_id: str, case: Case) -> str:
    """Generate a simulated legal draft (to be replaced with AI model)."""
    today = datetime.now().strftime("%d/%m/%Y")
    court = case.court or "High Court"
    title = case.title or "Case"
    case_number = case.case_number or "___/2026"

    templates = {
        "bail-application": f"""IN THE {court.upper()}

CRIMINAL MISCELLANEOUS APPLICATION No. {case_number}

IN THE MATTER OF:
{title}

APPLICATION UNDER SECTION 439 OF THE CODE OF CRIMINAL PROCEDURE, 1973

MOST RESPECTFULLY SHOWETH:

1. That the applicant/accused is a law-abiding citizen with deep roots in the community.

2. That the applicant was arrested in connection with the above referenced case.

3. That the charge sheet was filed beyond the statutory period of 90 days as prescribed under Section 167(2) of CrPC, thereby entitling the applicant to default bail as a matter of right.

4. That the investigation is complete and the charge sheet has been filed. The applicant is no longer required for the purpose of investigation.

5. That the applicant undertakes to cooperate with the court proceedings and shall not tamper with evidence or influence witnesses.

PRAYER:
In view of the above, it is most respectfully prayed that this Hon'ble Court may be pleased to grant regular bail to the applicant in the interest of justice.

AND FOR THIS ACT OF KINDNESS, THE APPLICANT SHALL EVER PRAY.

ADVOCATE FOR THE APPLICANT
Date: {today}
Place: New Delhi""",
        "written-arguments": f"""IN THE {court.upper()}

{title}
Case No. {case_number}

WRITTEN ARGUMENTS ON BEHALF OF THE DEFENCE

1. PRELIMINARY SUBMISSIONS
The defence respectfully submits these written arguments for the kind consideration of this Hon'ble Court.

2. FACTUAL MATRIX
The facts of the case as established through evidence on record are submitted herein.

3. LEGAL ARGUMENTS
The defence relies on the following legal provisions and precedents in support of its case.

4. PRAYER
In view of the submissions made above, the defence prays that this Hon'ble Court may be pleased to pass appropriate orders in favour of the accused.

Date: {today}
COUNSEL FOR THE DEFENCE""",
    }

    return templates.get(template_id, f"""LEGAL DOCUMENT

Case: {title}
Case No.: {case_number}
Court: {court}

[Draft generated by KanoonEdge AI on {today}]

This document has been auto-generated based on the case information available. Please review and customize before filing.

Date: {today}""")


@router.get("/templates", response_model=List[DraftTemplateResponse])
async def get_templates():
    """Get available draft templates."""
    return TEMPLATES


@router.post("/generate", response_model=DraftResponse)
async def generate_draft(
    request: DraftRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Generate a legal draft document."""
    case = db.query(Case).filter(Case.id == request.case_id, Case.user_id == current_user.id).first()
    if not case:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Case not found")

    content = _generate_draft_content(request.template_id, case)

    draft = Draft(
        case_id=case.id,
        draft_type=request.template_id,
        content=content,
    )
    db.add(draft)
    db.commit()
    db.refresh(draft)

    return DraftResponse(
        id=draft.id,
        template_id=request.template_id,
        content=draft.content,
        status="generated",
    )


@router.get("/{case_id}", response_model=List[DraftResponse])
async def list_drafts(
    case_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """List all drafts for a case."""
    case = db.query(Case).filter(Case.id == case_id, Case.user_id == current_user.id).first()
    if not case:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Case not found")
    drafts = db.query(Draft).filter(Draft.case_id == case_id).order_by(Draft.created_at.desc()).all()
    return [DraftResponse(id=d.id, template_id=d.draft_type, content=d.content, status="generated") for d in drafts]
