from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List

from app.database import get_db
from app.models import User, Case, TimelineEvent
from app.schemas.timeline import TimelineEventCreate, TimelineEventResponse
from app.utils.auth import get_current_user

router = APIRouter()


def _event_to_response(e: TimelineEvent) -> TimelineEventResponse:
    return TimelineEventResponse(
        id=e.id,
        eventType=e.event_type,
        title=e.title,
        description=e.description,
        eventDate=e.event_date,
        status=e.status or "completed",
        autoGenerated=e.auto_generated or False,
        linkedDocumentId=e.linked_document_id,
        linkedHearingId=e.linked_hearing_id,
        createdAt=e.created_at.strftime("%Y-%m-%dT%H:%M:%S") if e.created_at else "",
    )


@router.get("/{case_id}", response_model=List[TimelineEventResponse])
async def get_timeline(
    case_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    case = db.query(Case).filter(Case.id == case_id, Case.user_id == current_user.id).first()
    if not case:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Case not found")
    events = db.query(TimelineEvent).filter(
        TimelineEvent.case_id == case_id
    ).order_by(TimelineEvent.event_date.desc()).all()
    return [_event_to_response(e) for e in events]


@router.post("/{case_id}", response_model=TimelineEventResponse, status_code=status.HTTP_201_CREATED)
async def add_timeline_event(
    case_id: str,
    data: TimelineEventCreate,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    case = db.query(Case).filter(Case.id == case_id, Case.user_id == current_user.id).first()
    if not case:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Case not found")
    event = TimelineEvent(
        case_id=case_id,
        event_type=data.event_type,
        title=data.title,
        description=data.description,
        event_date=data.event_date,
        status=data.status or "completed",
        auto_generated=False,
        linked_document_id=data.linked_document_id,
        linked_hearing_id=data.linked_hearing_id,
    )
    db.add(event)
    db.commit()
    db.refresh(event)
    return _event_to_response(event)


@router.delete("/{event_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_timeline_event(
    event_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    event = db.query(TimelineEvent).filter(TimelineEvent.id == event_id).first()
    if not event:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Event not found")
    case = db.query(Case).filter(Case.id == event.case_id, Case.user_id == current_user.id).first()
    if not case:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not authorized")
    db.delete(event)
    db.commit()
