from pydantic import BaseModel
from typing import Optional


class TimelineEventCreate(BaseModel):
    event_type: str = "custom"
    title: str
    description: Optional[str] = None
    event_date: str
    status: Optional[str] = "completed"
    linked_document_id: Optional[str] = None
    linked_hearing_id: Optional[str] = None


class TimelineEventResponse(BaseModel):
    id: str
    eventType: str
    title: str
    description: Optional[str] = None
    eventDate: str
    status: str
    autoGenerated: bool = False
    linkedDocumentId: Optional[str] = None
    linkedHearingId: Optional[str] = None
    createdAt: str
